### ISSUE TITLE
关于本项目的建议

### ISSUE THREAD

**Issue by LimeZky** [CoolQ/Cup#10]
1，建议添加近30-90天内的可用率折线图，当点击具体项目时显示
2，建议添加分类功能，聚合几个项目为一个分组，点击显示
3，建议添加事件日志（维护日志），示例如图
![image](https://user-images.githubusercontent.com/31511420/82121945-39102e00-97c3-11ea-8933-c15b9b92a22c.png)
4，建议添加腾讯云云拔测数据来源，其对国内网站和服务器有着更好的支持，数据更加准确
5，建议添加项目详细信息，当点击时可以展示（如链接等）
6，请问项目根目录下的CNAME文件作用是什么，是否可以删去

**Comment by Coxxs** [comment]
Hi，感谢详细建议。该项目暂未处于活跃开发状态，您可以 Fork 之后自行改进。

关于第六点，请参考 https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site
